/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminVisaoGeralRouteImport } from './routes/_authenticated/admin.visao-geral'
import { Route as AuthenticatedAdminJuridicoRouteImport } from './routes/_authenticated/admin.juridico'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin.crm'
import { Route as AuthenticatedAdminBibliotecaMidiaRouteImport } from './routes/_authenticated/admin.biblioteca-midia'
import { Route as ApiPublicGoogleCalendarCallbackRouteImport } from './routes/api/public/google-calendar.callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVisaoGeralRoute =
  AuthenticatedAdminVisaoGeralRouteImport.update({
    id: '/visao-geral',
    path: '/visao-geral',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJuridicoRoute =
  AuthenticatedAdminJuridicoRouteImport.update({
    id: '/juridico',
    path: '/juridico',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBibliotecaMidiaRoute =
  AuthenticatedAdminBibliotecaMidiaRouteImport.update({
    id: '/biblioteca-midia',
    path: '/biblioteca-midia',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicGoogleCalendarCallbackRoute =
  ApiPublicGoogleCalendarCallbackRouteImport.update({
    id: '/api/public/google-calendar/callback',
    path: '/api/public/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/admin/biblioteca-midia': typeof AuthenticatedAdminBibliotecaMidiaRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/juridico': typeof AuthenticatedAdminJuridicoRoute
  '/admin/visao-geral': typeof AuthenticatedAdminVisaoGeralRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/admin/biblioteca-midia': typeof AuthenticatedAdminBibliotecaMidiaRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/juridico': typeof AuthenticatedAdminJuridicoRoute
  '/admin/visao-geral': typeof AuthenticatedAdminVisaoGeralRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/admin/biblioteca-midia': typeof AuthenticatedAdminBibliotecaMidiaRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/juridico': typeof AuthenticatedAdminJuridicoRoute
  '/_authenticated/admin/visao-geral': typeof AuthenticatedAdminVisaoGeralRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/portal'
    | '/admin/biblioteca-midia'
    | '/admin/crm'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/juridico'
    | '/admin/visao-geral'
    | '/api/public/google-calendar/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/portal'
    | '/admin/biblioteca-midia'
    | '/admin/crm'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/juridico'
    | '/admin/visao-geral'
    | '/api/public/google-calendar/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/portal'
    | '/_authenticated/admin/biblioteca-midia'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/juridico'
    | '/_authenticated/admin/visao-geral'
    | '/api/public/google-calendar/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicGoogleCalendarCallbackRoute: typeof ApiPublicGoogleCalendarCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/visao-geral': {
      id: '/_authenticated/admin/visao-geral'
      path: '/visao-geral'
      fullPath: '/admin/visao-geral'
      preLoaderRoute: typeof AuthenticatedAdminVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/juridico': {
      id: '/_authenticated/admin/juridico'
      path: '/juridico'
      fullPath: '/admin/juridico'
      preLoaderRoute: typeof AuthenticatedAdminJuridicoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/biblioteca-midia': {
      id: '/_authenticated/admin/biblioteca-midia'
      path: '/biblioteca-midia'
      fullPath: '/admin/biblioteca-midia'
      preLoaderRoute: typeof AuthenticatedAdminBibliotecaMidiaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/google-calendar/callback': {
      id: '/api/public/google-calendar/callback'
      path: '/api/public/google-calendar/callback'
      fullPath: '/api/public/google-calendar/callback'
      preLoaderRoute: typeof ApiPublicGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBibliotecaMidiaRoute: typeof AuthenticatedAdminBibliotecaMidiaRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminJuridicoRoute: typeof AuthenticatedAdminJuridicoRoute
  AuthenticatedAdminVisaoGeralRoute: typeof AuthenticatedAdminVisaoGeralRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBibliotecaMidiaRoute:
    AuthenticatedAdminBibliotecaMidiaRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminJuridicoRoute: AuthenticatedAdminJuridicoRoute,
  AuthenticatedAdminVisaoGeralRoute: AuthenticatedAdminVisaoGeralRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicGoogleCalendarCallbackRoute: ApiPublicGoogleCalendarCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
