/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedMeuPortalRouteImport } from './routes/_authenticated/meu-portal'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminVisaoGeralRouteImport } from './routes/_authenticated/admin.visao-geral'
import { Route as AuthenticatedAdminSprintRouteImport } from './routes/_authenticated/admin.sprint'
import { Route as AuthenticatedAdminPortalConteudosRouteImport } from './routes/_authenticated/admin.portal-conteudos'
import { Route as AuthenticatedAdminJuridicoRouteImport } from './routes/_authenticated/admin.juridico'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin.financeiro'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin.crm'
import { Route as AuthenticatedAdminCadastrosRouteImport } from './routes/_authenticated/admin.cadastros'
import { Route as AuthenticatedAdminBibliotecaMidiaRouteImport } from './routes/_authenticated/admin.biblioteca-midia'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'
import { Route as ApiPublicMetaBusinessCallbackRouteImport } from './routes/api/public/meta-business.callback'
import { Route as ApiPublicGoogleCalendarCallbackRouteImport } from './routes/api/public/google-calendar.callback'
import { Route as AuthenticatedAdminClientesClienteIdRouteImport } from './routes/_authenticated/admin.clientes.$clienteId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuPortalRoute = AuthenticatedMeuPortalRouteImport.update({
  id: '/meu-portal',
  path: '/meu-portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVisaoGeralRoute =
  AuthenticatedAdminVisaoGeralRouteImport.update({
    id: '/visao-geral',
    path: '/visao-geral',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSprintRoute =
  AuthenticatedAdminSprintRouteImport.update({
    id: '/sprint',
    path: '/sprint',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPortalConteudosRoute =
  AuthenticatedAdminPortalConteudosRouteImport.update({
    id: '/portal-conteudos',
    path: '/portal-conteudos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJuridicoRoute =
  AuthenticatedAdminJuridicoRouteImport.update({
    id: '/juridico',
    path: '/juridico',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCadastrosRoute =
  AuthenticatedAdminCadastrosRouteImport.update({
    id: '/cadastros',
    path: '/cadastros',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBibliotecaMidiaRoute =
  AuthenticatedAdminBibliotecaMidiaRouteImport.update({
    id: '/biblioteca-midia',
    path: '/biblioteca-midia',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaBusinessCallbackRoute =
  ApiPublicMetaBusinessCallbackRouteImport.update({
    id: '/api/public/meta-business/callback',
    path: '/api/public/meta-business/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCalendarCallbackRoute =
  ApiPublicGoogleCalendarCallbackRouteImport.update({
    id: '/api/public/google-calendar/callback',
    path: '/api/public/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminClientesClienteIdRoute =
  AuthenticatedAdminClientesClienteIdRouteImport.update({
    id: '/clientes/$clienteId',
    path: '/clientes/$clienteId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/meu-portal': typeof AuthenticatedMeuPortalRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/admin/biblioteca-midia': typeof AuthenticatedAdminBibliotecaMidiaRoute
  '/admin/cadastros': typeof AuthenticatedAdminCadastrosRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/juridico': typeof AuthenticatedAdminJuridicoRoute
  '/admin/portal-conteudos': typeof AuthenticatedAdminPortalConteudosRoute
  '/admin/sprint': typeof AuthenticatedAdminSprintRoute
  '/admin/visao-geral': typeof AuthenticatedAdminVisaoGeralRoute
  '/admin/clientes/$clienteId': typeof AuthenticatedAdminClientesClienteIdRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/meta-business/callback': typeof ApiPublicMetaBusinessCallbackRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/meu-portal': typeof AuthenticatedMeuPortalRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/admin/biblioteca-midia': typeof AuthenticatedAdminBibliotecaMidiaRoute
  '/admin/cadastros': typeof AuthenticatedAdminCadastrosRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/juridico': typeof AuthenticatedAdminJuridicoRoute
  '/admin/portal-conteudos': typeof AuthenticatedAdminPortalConteudosRoute
  '/admin/sprint': typeof AuthenticatedAdminSprintRoute
  '/admin/visao-geral': typeof AuthenticatedAdminVisaoGeralRoute
  '/admin/clientes/$clienteId': typeof AuthenticatedAdminClientesClienteIdRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/meta-business/callback': typeof ApiPublicMetaBusinessCallbackRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/meu-portal': typeof AuthenticatedMeuPortalRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/admin/biblioteca-midia': typeof AuthenticatedAdminBibliotecaMidiaRoute
  '/_authenticated/admin/cadastros': typeof AuthenticatedAdminCadastrosRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/juridico': typeof AuthenticatedAdminJuridicoRoute
  '/_authenticated/admin/portal-conteudos': typeof AuthenticatedAdminPortalConteudosRoute
  '/_authenticated/admin/sprint': typeof AuthenticatedAdminSprintRoute
  '/_authenticated/admin/visao-geral': typeof AuthenticatedAdminVisaoGeralRoute
  '/_authenticated/admin/clientes/$clienteId': typeof AuthenticatedAdminClientesClienteIdRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/meta-business/callback': typeof ApiPublicMetaBusinessCallbackRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/login'
    | '/admin'
    | '/app'
    | '/meu-portal'
    | '/portal'
    | '/admin/biblioteca-midia'
    | '/admin/cadastros'
    | '/admin/crm'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/juridico'
    | '/admin/portal-conteudos'
    | '/admin/sprint'
    | '/admin/visao-geral'
    | '/admin/clientes/$clienteId'
    | '/api/public/google-calendar/callback'
    | '/api/public/meta-business/callback'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/login'
    | '/admin'
    | '/app'
    | '/meu-portal'
    | '/portal'
    | '/admin/biblioteca-midia'
    | '/admin/cadastros'
    | '/admin/crm'
    | '/admin/equipe'
    | '/admin/financeiro'
    | '/admin/juridico'
    | '/admin/portal-conteudos'
    | '/admin/sprint'
    | '/admin/visao-geral'
    | '/admin/clientes/$clienteId'
    | '/api/public/google-calendar/callback'
    | '/api/public/meta-business/callback'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cadastro'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/meu-portal'
    | '/_authenticated/portal'
    | '/_authenticated/admin/biblioteca-midia'
    | '/_authenticated/admin/cadastros'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/juridico'
    | '/_authenticated/admin/portal-conteudos'
    | '/_authenticated/admin/sprint'
    | '/_authenticated/admin/visao-geral'
    | '/_authenticated/admin/clientes/$clienteId'
    | '/api/public/google-calendar/callback'
    | '/api/public/meta-business/callback'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  ApiPublicGoogleCalendarCallbackRoute: typeof ApiPublicGoogleCalendarCallbackRoute
  ApiPublicMetaBusinessCallbackRoute: typeof ApiPublicMetaBusinessCallbackRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-portal': {
      id: '/_authenticated/meu-portal'
      path: '/meu-portal'
      fullPath: '/meu-portal'
      preLoaderRoute: typeof AuthenticatedMeuPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/visao-geral': {
      id: '/_authenticated/admin/visao-geral'
      path: '/visao-geral'
      fullPath: '/admin/visao-geral'
      preLoaderRoute: typeof AuthenticatedAdminVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sprint': {
      id: '/_authenticated/admin/sprint'
      path: '/sprint'
      fullPath: '/admin/sprint'
      preLoaderRoute: typeof AuthenticatedAdminSprintRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portal-conteudos': {
      id: '/_authenticated/admin/portal-conteudos'
      path: '/portal-conteudos'
      fullPath: '/admin/portal-conteudos'
      preLoaderRoute: typeof AuthenticatedAdminPortalConteudosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/juridico': {
      id: '/_authenticated/admin/juridico'
      path: '/juridico'
      fullPath: '/admin/juridico'
      preLoaderRoute: typeof AuthenticatedAdminJuridicoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cadastros': {
      id: '/_authenticated/admin/cadastros'
      path: '/cadastros'
      fullPath: '/admin/cadastros'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/biblioteca-midia': {
      id: '/_authenticated/admin/biblioteca-midia'
      path: '/biblioteca-midia'
      fullPath: '/admin/biblioteca-midia'
      preLoaderRoute: typeof AuthenticatedAdminBibliotecaMidiaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-business/callback': {
      id: '/api/public/meta-business/callback'
      path: '/api/public/meta-business/callback'
      fullPath: '/api/public/meta-business/callback'
      preLoaderRoute: typeof ApiPublicMetaBusinessCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar/callback': {
      id: '/api/public/google-calendar/callback'
      path: '/api/public/google-calendar/callback'
      fullPath: '/api/public/google-calendar/callback'
      preLoaderRoute: typeof ApiPublicGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/clientes/$clienteId': {
      id: '/_authenticated/admin/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/admin/clientes/$clienteId'
      preLoaderRoute: typeof AuthenticatedAdminClientesClienteIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBibliotecaMidiaRoute: typeof AuthenticatedAdminBibliotecaMidiaRoute
  AuthenticatedAdminCadastrosRoute: typeof AuthenticatedAdminCadastrosRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminJuridicoRoute: typeof AuthenticatedAdminJuridicoRoute
  AuthenticatedAdminPortalConteudosRoute: typeof AuthenticatedAdminPortalConteudosRoute
  AuthenticatedAdminSprintRoute: typeof AuthenticatedAdminSprintRoute
  AuthenticatedAdminVisaoGeralRoute: typeof AuthenticatedAdminVisaoGeralRoute
  AuthenticatedAdminClientesClienteIdRoute: typeof AuthenticatedAdminClientesClienteIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBibliotecaMidiaRoute:
    AuthenticatedAdminBibliotecaMidiaRoute,
  AuthenticatedAdminCadastrosRoute: AuthenticatedAdminCadastrosRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminJuridicoRoute: AuthenticatedAdminJuridicoRoute,
  AuthenticatedAdminPortalConteudosRoute:
    AuthenticatedAdminPortalConteudosRoute,
  AuthenticatedAdminSprintRoute: AuthenticatedAdminSprintRoute,
  AuthenticatedAdminVisaoGeralRoute: AuthenticatedAdminVisaoGeralRoute,
  AuthenticatedAdminClientesClienteIdRoute:
    AuthenticatedAdminClientesClienteIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedMeuPortalRoute: typeof AuthenticatedMeuPortalRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedMeuPortalRoute: AuthenticatedMeuPortalRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  ApiPublicGoogleCalendarCallbackRoute: ApiPublicGoogleCalendarCallbackRoute,
  ApiPublicMetaBusinessCallbackRoute: ApiPublicMetaBusinessCallbackRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
